### ISSUE TITLE
Is there an object-oriented version available?

### ISSUE THREAD

**Issue by moodmosaic** [ploeh/KataTennis#1]
I was reading [this](https://github.com/AutoFixture/AutoFixture/pull/529#issuecomment-186814698) comment and noticed that a test shown there _may_ actually be from this same Kata:

``` c#
[Theory, AutoTennisData]
public void PlayerOneWinsReturnsResultWithCorrectScoreForPlayerOne(
    [Greedy]Game sut, IPoints newPoints)
{
    Mock.Get(sut.PlayerTwoScore).Setup(p => p.Accept(sut.PlayerOneScore)).Returns(newPoints);
    var result = sut.PlayerOneWinsBall();
    Assert.Equal(newPoints, result.PlayerOneScore);
}
```

The test shown in that comment demonstrate _state of the art_ object-oriented design, which IMHO can only be found in a few places
- [AtomEventStore](https://github.com/GreanTech/AtomEventStore)
- [Albedo](https://github.com/ploeh/Albedo)
- [Advanced Unit Testing](https://app.pluralsight.com/library/courses/advanced-unit-testing/) course on Pluralsight 
- [AutoFixture](https://github.com/AutoFixture/AutoFixture) (most of the codebase)

Such object-oriented design is something I consider beautiful, rare and hard to find, and I was wondering if there's also an object-oriented version of this Kata available.

---

If there _is_ an object-oriented version of this Kata available, it can act as a great example for comparing good object-oriented design and good functional design side-by-side, e.g.

| OO | FP |
| :-: | :-: |
| Visitor | Pattern Matching |
| Test Doubles | Higher-order functions |

and so on.

**Comment by ploeh** [comment]
IIRC it comes from [this article](http://blog.ploeh.dk/2011/05/16/TennisKatawithimmutabletypesandacyclomaticcomplexityof1).

**Comment by moodmosaic** [comment]
Thank you. Yes, it is.
